#! /usr/bin/env python
"""
This file acts as a standalone command-line interface to the 
`abscal.common.mast.download_mast_program` function. That function allows the download of 
one or more HST programs, from MAST, to a designated directory.

Author
-------
- Brian York

Use
---
This file is intended to be run from the command line::

    download_mast [options] program(s)
"""

from abscal.common.mast import main as run_mast


def main():
    run_mast()


if __name__ == "__main__":
    main()
